Repository apache/incubator-openwhisk-runtime-nodejs, pull requests merged in 2018-04, with the labels that each got.

#39 Add scancode to Travis using the ASF Release configuration.
  core/nodejs8Action/build.gradle
  tools/travis/build.sh
  tools/travis/setup.sh
Labels: build, review

#40 Fix comments in setup.sh to reflect why we are cloning repos.
  tools/travis/setup.sh
Labels: build, documentation

#38 Add the licenses of the dependencies into LICENSE
  LICENSE.txt
  licenses/LICENSE-XMLHttpRequest.txt
  licenses/LICENSE-apn.txt
  licenses/LICENSE-async.txt
  licenses/LICENSE-bodyparser.txt
  licenses/LICENSE-btoa.txt
  licenses/LICENSE-cheerio.txt
  licenses/LICENSE-cloudant.txt
  licenses/LICENSE-commander.txt
  licenses/LICENSE-consul.txt
  licenses/LICENSE-cookieparser.txt
  licenses/LICENSE-cradle.txt
  licenses/LICENSE-errorhandler.txt
  licenses/LICENSE-express.txt
  licenses/LICENSE-expresssession.txt
  licenses/LICENSE-glob.txt
  licenses/LICENSE-gm.txt
  licenses/LICENSE-iconvlite.txt
  licenses/LICENSE-lodash.txt
  licenses/LICENSE-log4js.txt
  licenses/LICENSE-marked.txt
  licenses/LICENSE-merge.txt
  licenses/LICENSE-moment.txt
  licenses/LICENSE-mongodb.txt
  licenses/LICENSE-mustache.txt
  licenses/LICENSE-nano.txt
  licenses/LICENSE-node.txt
  licenses/LICENSE-nodemailer.txt
  licenses/LICENSE-nodeserver.txt
  licenses/LICENSE-nodeuuid.txt
  licenses/LICENSE-openwhisk.txt
  licenses/LICENSE-pkgcloud.txt
  licenses/LICENSE-process.txt
  licenses/LICENSE-redis.txt
  licenses/LICENSE-request.txt
  licenses/LICENSE-requestpromise.txt
  licenses/LICENSE-rimraf.txt
  licenses/LICENSE-semver.txt
  licenses/LICENSE-sendgrid.txt
  licenses/LICENSE-servefavicon.txt
  licenses/LICENSE-socketio.txt
  licenses/LICENSE-socketioclient.txt
  licenses/LICENSE-superagent.txt
  licenses/LICENSE-swaggertools.txt
  licenses/LICENSE-tmp.txt
  licenses/LICENSE-twilio.txt
  licenses/LICENSE-underscore.txt
  licenses/LICENSE-uuid.txt
  licenses/LICENSE-validator.txt
  licenses/LICENSE-watsondevelopercloud.txt
  licenses/LICENSE-when.txt
  licenses/LICENSE-winston.txt
  licenses/LICENSE-ws.txt
  licenses/LICENSE-xml2js.txt
  licenses/LICENSE-yauzl.txt
Labels: review
